Document: libfn
Title: Debian libfn Manual
Author: <insert document author here>
Abstract: This manual describes what libfn is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libfn/libfn.sgml.gz

Format: postscript
Files: /usr/share/doc/libfn/libfn.ps.gz

Format: text
Files: /usr/share/doc/libfn/libfn.text.gz

Format: HTML
Index: /usr/share/doc/libfn/html/index.html
Files: /usr/share/doc/libfn/html/*.html
